[package]
name = "prak-cmc-sem03"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "kr0_t1"
path = "src/bin/kr0/kr0_t1.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
